---
title: "groupFormation"
author: "Clara Lavrador"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




### Life Cycle

## Model

### Packages 
```{r packages}

library(ggplot2)
library(igraph)
library(network)
library(networkDynamic)
library(intergraph)
library(ndtv)

```


### Parameters
```{r parameters}

#number of agents to generate
popSize <- 100

pursuitRange <- c(1:5)

#number of pursuits each agent will have for each reassessment period
pursuitAmount <- 4

#number of times agents will reevaluate their pursuits
reassessments <- 30

#number of loops for the whole model
modelLoops <- 10

#to normalize euclidean distances, divide by highest possible euclidean distance considering vector length and range
maxEuc <- 174

```


### Functions
```{r functions}


#Agent Generate Function#

agentGenerate <- function(n){
  
  #randomly generate 3 traits and their corresponding preferences for each agent
  trait1 <- sample(c(1:100), n, replace = T)
  
  trait2 <- sample(c(1:100), n, replace = T)
  
  trait3 <- sample(c(1:100), n, replace = T)
  
  pref1 <- sample(c(1:100), n, replace = T)
  
  pref2 <- sample(c(1:100), n, replace = T)
  
  pref3 <- sample(c(1:100), n, replace = T)
  
  #put it all together in a df
  agents <- data.frame(trait1, trait2, trait3, pref1, pref2, pref3)
  
  return(agents)
  
}



#Euclidean Distance Function#
#calculates distances between agent a's traits and agent b's preferences

euc.dist <- function(x1, x2) sqrt(sum((x1 - x2) ^ 2))



#Alliance Score Function#
#input an agent, output vector of alliance values of all other agents for input agent

alliance <- function(agent, agents){

    #pull all agents' trait columns 
    trait_cols <- agents[, c("trait1","trait2","trait3")]
    
    #pull the input agent's preference columns
    pref_cols <- agents[agent, c("pref1","pref2","pref3")]
    
    #calculate the euclidean distance between each row of trait cols with agent's pref cols
   alliance_values <- apply(trait_cols, 1, function(trait_row) {
     euc.dist(pref_cols, trait_row)
  
     
   })
    
   #normalize by dividing by max euc, and subtract from 1 to reverse the scale (let's make bigger be better)
   alliance_values <- 1 - (alliance_values/maxEuc)
   
   #return the vector of alliance values for the inputted agent
   return(alliance_values)
   
  }
  



#Overlap Score Function#
#calculates overlap between input agent and all other agents by comparing their sent and received pursuits; based on Dave's triadic primitives

overlap <- function(agent, adjMat) {
     
  
       #Alliance#
       #calculate correlation of agent's row with other agents' rows
  
      alliance <- apply(adjMat, 1, function(x)
        cor(x, adjMat[agent, ], use = "complete.obs"))
      
      #change NAs to 0
      alliance [is.na(alliance)] <- 0
      
      #add 1 to make them positive (unless it is 0, being in the first reassessment)
      alliance <- ifelse(alliance != 0, alliance + 1, 0)    
      
     
      
      #Displacement#
      #calculate correlation of agent's row with other agents' columns
      
      displacement <- apply(adjMat, 2, function(x)
        cor(x, adjMat[agent, ], use = "complete.obs"))
      
      #change NAs to 0
      displacement [is.na(displacement)] <- 0
      
      #add 1 to make them positive
      displacement <- ifelse(displacement != 0, displacement + 1, 0)
      
      
      
      
      #Defense#
      #calculate correlation of agent's column with other agents' rows
      
      defense <- apply(adjMat, 1, function(x)
        cor(x, adjMat[, agent], use = "complete.obs"))
      
      #change NAs to 0
      defense [is.na(defense)] <- 0
      
      #add 1 to make them positive
      defense <- ifelse(defense != 0, defense + 1, 0)
      
      
      
      
      #Generalization#
      #calculate correlation of agent's column with other agents' columns
      
      generalization <- apply(adjMat, 2, function(x)
        cor(x, adjMat[, agent], use = "complete.obs"))
      
      #change NAs to 0
      generalization [is.na(generalization)] <- 0
      
      #add 1 to make them positive
      generalization <- ifelse(generalization != 0, generalization + 1, 0)
      
      
      
      #add together the 4 primitives to get the overlap scores
      overlap_scores <- alliance + displacement + generalization + defense
      
      overlap_scores[agent] <- NA
      
      return(overlap_scores)
      
    }
    
  
#Reciprocity Function#

reciprocity <- function(agent, adjMat){
  
  #pull agent's column which represents their received pursuits
  received <- adjMat[,agent]
  
  #pull agent's row which represents their sent pursuits
  sent <- adjMat[agent,]
    
  #calculate proportions of pursuits which were received, multiply by 2 to match overlap components' range
  reciprocity_scores <- 2*(received / (received + sent))
  
  #nullify their own reciprocity score
  reciprocity_scores[agent] <- NA
  
  return(reciprocity_scores)
  
  
}
  


```


### Life Cycle

```{r lifeCycle}


#initialize results df
results <- data.frame("loop" = rep(1:modelLoops,each = reassessments),
                      "reassess" = rep(1:reassessments),
                      "num_groups" = NA,
                      "num_recip_edges" = NA)




for(m in 1:modelLoops) {
  
  #generate agents
  agents <- agentGenerate(popSize)

  #generate adjacency matrix (populate with 1)
  adjMat <- matrix(1, nrow = popSize, ncol = popSize)
  
  #store each reassessment period's cumulative adjacency matrix so that agents can reference the previous one when calculating their overlap/reciprocal scores
  matrix_list <- list(adjMat)
  
  #initialize list to store each reassessment's adjacency matrix as binary for that iteration so we can look at who was reciprocal at each reassessment period
  noncumMat_list <- list(adjMat)

  #for each reassessment... (agents look backwards so start from 2)
  for (t in 2:reassessments) {
    
    #create the empty noncumulative adjacency matrix
    noncumMat <- matrix(0, nrow = popSize, ncol = popSize)
    
    #for each agent...
    for (a in 1:nrow(agents)) {
      
      #calculate the overlap scores between themselves and the other agents
      overlap_scores <- overlap(a, matrix_list[[t - 1]])
      
      #calculate the reciprocity scores between themselves and the other agents
      reciprocity_scores <- reciprocity(a, matrix_list[[t - 1]])
      
      #calculate the alliance values between their prefs and the other agents' traits
      alliance_values <- alliance(a, agents)
      
      #Combine overlap, reciprocity, and alliance scores into single calculation
      pursuit_scores <- (overlap_scores + reciprocity_scores) * (alliance_values)
      
      #Randomize number of pursuits for the agent
      #pursuitAmount <- sample(pursuitRange, 1, replace = T)
      
      #sort by product in descending order and get the indices of the top value agents
      pursuit_indices <- order(-pursuit_scores)[1:pursuitAmount]
      
      #add 1 to their pursuits in the cumulative the adjacency matrix
      adjMat[a, pursuit_indices] <- adjMat[a, pursuit_indices] + 1
      
      #and to the individual one
      noncumMat[a, pursuit_indices] <- 1
      
      
    }
    
    #add the adjMat to the matrix list
    matrix_list[[t]] <- adjMat
    
    #add the non cumulative matrix to its list
    noncumMat_list[[t]] <- noncumMat
    
  }
  
  
  #convert the noncum adjacency matrices into igraph networks
  igraph_list <- lapply(noncumMat_list, graph_from_adjacency_matrix)
  
  #loop through each igraph object
  for (g in 1:length(igraph_list)) {
    
    #only include edges that are reciprocated
    igraph_list[[g]] <- subgraph.edges(igraph_list[[g]],
                                              E(igraph_list[[g]])[which_mutual(igraph_list[[g]])],
                                              delete.vertices = F) #maybe i can just do this with true to get groups
    
    #add number of reciprocal edges to results df
    results$num_recip_edges[results$loop == m & results$reassess == g] <- (length(subgraph.edges(igraph_list[[g]], E(igraph_list[[g]])[which_mutual(igraph_list[[g]])])))

  }
  
  #count number of groups
  
  no_isolates_igraph <- igraph_list
  
  for (g in 1:length(no_isolates_igraph)) {
    
    if (g > 1) {
      
      #first must delete the isolates or they will be counted as individual groups
      g.degree <- igraph::degree(no_isolates_igraph[[g]])
      g.isolates <- V(no_isolates_igraph[[g]])[which(g.degree < 1)]
      no_isolates_igraph[[g]] <- delete_vertices(no_isolates_igraph[[g]], g.isolates)
      
      #add to results df
      results$num_groups[results$loop == m & results$reassess == g] <- components(no_isolates_igraph[[g]])$no
      
    } else {
      
      #the first plot should have no edges at all
      results$num_groups[results$loop == m & results$reassess == g] <- 0
      
    }
    
  }
  
}

#the first reassess from each loop displays recip edge number as popSize because of intial matrix set up, so fix to 0
results$num_recip_edges[results$reassess == 1] <- 0


```

### Analysis

```{r analysis}



#Edge Count Plot#
#see how number of reciprocal edges changes over time across all model loops
ggplot(data = results,
       aes(x = reassess,
           y = num_recip_edges,
           color = as.factor(loop))) +
  labs(x = "regroup period",
       y = "number of reciprocated edges",
       color = "model loop") +
  geom_line()


#Group Count Plot#
#see how number of groups changes over time across all model loops
ggplot(data = results,
       aes(x = reassess,
           y = num_groups,
           color = as.factor(loop))) +
  labs(x = "regroup period",
       y = "number of groups",
       color = "model loop") +
  geom_smooth(fill = as.factor(loop)) +
  theme_bw()



### Plotting Networks
#we shall a dynamic network of just one loop (the last one)



#igraph list should already exist
# igraph_list <- lapply(noncumMat_list, igraph::graph_from_adjacency_matrix) 
# 
# for(g in 1:length(igraph_list)){
#   
#   igraph_list[[g]] <- subgraph.edges(igraph_list[[g]], E(igraph_list[[g]])[which_mutual(igraph_list[[g]])], delete.vertices = F)
#   
#   print(length(subgraph.edges(igraph_list[[g]], E(igraph_list[[g]])[which_mutual(igraph_list[[g]])])))
#   
# }


#convert the igraph to network objects
networkList <- lapply(igraph_list, asNetwork)


#create dynamic network from network list
dynamicNet <- networkDynamic(network.list = networkList, 
                                 vertex.pid = "vertex.names",
                                 base.net = 
                                 create.TEAs = T,)

#render the movie (oscar nominee?)
render.d3movie(dynamicNet)









# plot(igraph_list[[20]], 
#      layout = layout.fruchterman.reingold, 
#      #vertex.label = NA,
#      #  rescale = F,
#      layout = layout_with_kk,
#      vertex.size = 8,
#      vertex.label.color = "grey25",
#      vertex.shape = "circle",
#      edge.arrow.size = 0.3)
# 
# 
# 
# ### no isolates so we can get the number of groups for each graph
# 
# 
# no_isolates <- igraph_list
# 
# for(g in 1:length(no_isolates)){
#   
#   g.degree <- igraph::degree(no_isolates[[g]])
#   g.isolates <- V(no_isolates[[g]])[which(g.degree < 1)]
#   no_isolates[[g]] <- delete_vertices(no_isolates[[g]], g.isolates)
#   
# }






```












